export * from './layout/index';
export * from './login/login.component';
export * from './login/login.module';
export * from './register/register.component';
export * from './register/register.module';
export * from './home/home.component';
export * from './home/home.module';
export * from './minor-view/minor-view.component';
export * from './minor-view/minor-view.module';
